apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sokos-utbetalingsportalen-astro
  namespace: okonomi
  labels:
    team: okonomi

spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "0de8d01f-8ad0-4391-841c-55392956bc17" # 0000-GA-SOKOS-MF-Attestasjon
          - id: "e0023d91-26bc-4d5d-95ba-3148b6123afc" # 0000-GA-SOKOS-MF-OppdragsInfo
          - id: 48a80bbb-be45-4ef6-aab8-21604f057f47 # 0000-GA-SOKOS-MF-Venteregister
          - id: 7e0c2ad1-d0e7-4fa8-8169-7a9d68435644 # 0000-GA-SOKOS-MF-Fastedata
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      external:
        - host: sokos-oppdrag.dev-fss-pub.nais.io
  ingresses:
    - "https://sokos-utbetalingsportalen-astro.intern.dev.nav.no"
    - "https://sokos-utbetalingsportalen-astro.ansatt.dev.nav.no"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: '20m'
      memory: 128Mi

  env:

    - name: UTBETALINGSPORTALEN_URL
      value: sokos-utbetalingsportalen-astro.intern.dev.nav.no
    - name: UTBETALINGSPORTALEN_ENVIRONMENT
      value: q1

    # sokos-oppdrag
    - name: SOKOS_OPPDRAG_API
      value: https://sokos-oppdrag.dev-fss-pub.nais.io
    - name: SOKOS_OPPDRAG_API_AUDIENCE
      value: api://dev-fss.okonomi.sokos-oppdrag/.default
    - name: SOKOS_OPPDRAG_PROXY
      value: "/oppdrag-api"
