apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sokos-utbetalingsportalen-astro
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  ingresses:
    - 'https://sokos-utbetalingsportalen-astro.ansatt.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: sokos-utbetalingsportalen-astro
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
    sidecar:
      enabled: true
      autoLogin: true
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: '20m'
      memory: 128Mi