apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sokos-utbetalingsportalen-astro
  namespace: okonomi
  labels:
    team: okonomi

spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "e0023d91-26bc-4d5d-95ba-3148b6123afc" # 0000-GA-SOKOS-MF-OppdragsInfo-READ
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      external:
        - host: sokos-oppdrag.dev-fss-pub.nais.io
  ingresses:
    - "https://sokos-utbetalingsportalen-astro.intern.dev.nav.no"
    - "https://sokos-utbetalingsportalen-astro.ansatt.dev.nav.no"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: '20m'
      memory: 128Mi

  env:

    - name: APP_INGRESS
      value: https://sokos-utbetalingsportalen.intern.dev.nav.no
