name: 'Deploy main'
on:
  push:
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'
  packages: 'write'

jobs:
  build:
    name: 'build'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: pnpm/action-setup@v4
        with:
          version: '10'
          run_install: false

      - uses: 'actions/setup-node@v3'
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      - name: Sette pnpm-config
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm config set engine-strict true
          pnpm config set @navikt:registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: 'Build application'
        run: pnpm run build

      - name: 'Build and push'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: okonomi

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Deploy'
        uses: 'nais/deploy/actions/deploy@v2'
        env:
          CLUSTER: 'dev-gcp'
          RESOURCE: .nais/naiserator-q1.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}

  deploy-dev-qx:
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Deploy'
        uses: 'nais/deploy/actions/deploy@v2'
        env:
          CLUSTER: 'dev-gcp'
          RESOURCE: .nais/naiserator-qx.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}